# Generated by Django 4.1 on 2022-09-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='artist')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='album')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='year')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='length')),
                ('codec', models.CharField(blank=True, max_length=255, null=True, verbose_name='codec')),
                ('sample_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='sample_rate')),
                ('bitrate', models.CharField(blank=True, max_length=255, null=True, verbose_name='bitrate')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], null=True, verbose_name='rating')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='path')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
